### ISSUE TITLE
Can someone push their working version?

### ISSUE THREAD

**Issue by Chronal** [hamishivi/shrec#2]
Mine doesn't work and I know at least one of you has a version that doesn't crash.

**Comment by hamishivi** [comment]
My version works fine on the latest commit...... Maybe @miscoined would have an idea of previous builds that worked fine

**Comment by miscoined** [comment]
Afaik the last build that worked was 7732f7c (This is without any naive filtering implementation). If that's crashing there might be something wrong with your setup in particular. Post details?
